#!/bin/bash
docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
docker tag carlosthe19916/keycloak-postgres carlosthe19916/keycloak-postgres:$(git rev-parse --short HEAD);
docker tag carlosthe19916/keycloak-postgres-ha carlosthe19916/keycloak-postgres-ha:$(git rev-parse --short HEAD);
docker push carlosthe19916/keycloak-postgres
docker push carlosthe19916/keycloak-postgres-ha
